### ISSUE TITLE
Update PyPI, project and repo name for consistency

### ISSUE THREAD

**Issue by singingwolfboy** [vitalk/flask-humanize#4]
This project looks really useful! Unfortunately, the naming scheme for the project on GitHub and the project on PyPI don't match up, presumably because [the Flask-Humanize name was already taken](https://pypi.python.org/pypi/flask-humanize). However, that PyPI entry says that the home page is https://github.com/eg0r/flask-humanize, and that page points to a 404 on GitHub. In light of that, perhaps @eg0r would be willing to pass off the Flask-Humanize name on PyPI to this project, so that it's easier to find, install, and use?

**Comment by vitalk** [comment]
Thank you @singingwolfboy!

The only way to contact @eg0r is via the GitHub, so I would appreciate if he can free the "Flask-Humanize" name on PyPI. On the other hand I could rename this repository into "humanize-flask" for consistency with package name.

**Comment by eg0r** [comment]
No idea how you linked me to that GitHub repository but it's nothing to do with me. I don't own it.

Date: Tue, 15 Mar 2016 11:05:47 -0700

**Comment by vitalk** [comment]
> No idea how you linked me to that GitHub repository

The [PyPI page](https://pypi.python.org/pypi/flask-humanize) contains link to the https://github.com/eg0r/flask-humanize. Sorry for a trouble.

**Comment by eg0r** [comment]
No problem, must have been his old account?

Date: Tue, 15 Mar 2016 11:42:33 -0700

**Comment by vitalk** [comment]
Looks so – PyPi upload has been made 2015-05-17, your account created 2015-09-30. Thank you @eg0r for clarification.

**Comment by singingwolfboy** [comment]
Doing a bit more digging here, [the PyPI page](https://pypi.python.org/pypi/flask-humanize) says that the index entry is owned by "egorsmkv", which might be @egorsmkv on GitHub. @egorsmkv, do you own the "Flask-Humanize" name on PyPI? If so, can you release it to this project?

**Comment by egorsmkv** [comment]
I removed the package from PyPI, so the name can take.

**Comment by vitalk** [comment]
Thank you so much!

**Comment by egorsmkv** [comment]
Тебе спасибо. Я использую его в своём проекте.

**Comment by vitalk** [comment]
@egorsmkv :+1:
